--Drop tables if they exist
DROP TABLE IF EXISTS DEPT_EMP;
DROP TABLE IF EXISTS DEPT_MANAGER;
DROP TABLE IF EXISTS SALARIES;
DROP TABLE IF EXISTS EMPLOYEES;
DROP TABLE IF EXISTS TITLES;
DROP TABLE IF EXISTS DEPARTMENTS;

--Create tables
CREATE TABLE DEPARTMENTS (
    dept_no VARCHAR(10) NOT NULL,
    dept_name VARCHAR(30) NOT NULL,
    CONSTRAINT pk_DEPARTMENTS PRIMARY KEY (
        dept_no
     )
);

CREATE TABLE TITLES (
    title_id VARCHAR(10) NOT NULL,
    title VARCHAR(30) NOT NULL,
    CONSTRAINT pk_TITLES PRIMARY KEY (
        title_id
     )
);

CREATE TABLE EMPLOYEES (
    emp_no INT NOT NULL,
    emp_title_id VARCHAR NOT NULL,
    birth_date DATE NOT NULL,
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    sex VARCHAR(10) NOT NULL,
    hire_date DATE NOT NULL,
    CONSTRAINT pk_EMPLOYEES PRIMARY KEY (
        emp_no
     )
);

CREATE TABLE SALARIES (
    emp_no INT NOT NULL,
    salary FLOAT NOT NULL,
    CONSTRAINT pk_SALARIES PRIMARY KEY (
        emp_no,salary
     )
);

CREATE TABLE DEPT_MANAGER (
    dept_no VARCHAR NOT NULL,
    emp_no INT NOT NULL,
    CONSTRAINT pk_DEPT_MANAGER PRIMARY KEY (
        dept_no,emp_no
     )
);

CREATE TABLE DEPT_EMP (
    emp_no INT NOT NULL,
    dept_no VARCHAR NOT NULL,
    CONSTRAINT pk_DEPT_EMP PRIMARY KEY (
        emp_no,dept_no
     )
);

ALTER TABLE EMPLOYEES ADD CONSTRAINT fk_EMPLOYEES_emp_title_id FOREIGN KEY(emp_title_id)
REFERENCES TITLES (title_id);

ALTER TABLE SALARIES ADD CONSTRAINT fk_SALARIES_emp_no FOREIGN KEY(emp_no)
REFERENCES EMPLOYEES (emp_no);

ALTER TABLE DEPT_MANAGER ADD CONSTRAINT fk_DEPT_MANAGER_dept_no FOREIGN KEY(dept_no)
REFERENCES DEPARTMENTS (dept_no);

ALTER TABLE DEPT_MANAGER ADD CONSTRAINT fk_DEPT_MANAGER_emp_no FOREIGN KEY(emp_no)
REFERENCES EMPLOYEES (emp_no);

ALTER TABLE DEPT_EMP ADD CONSTRAINT fk_DEPT_EMP_emp_no FOREIGN KEY(emp_no)
REFERENCES EMPLOYEES (emp_no);

ALTER TABLE DEPT_EMP ADD CONSTRAINT fk_DEPT_EMP_dept_no FOREIGN KEY(dept_no)
REFERENCES DEPARTMENTS (dept_no);